#
# WandItem: item used in game to throw a fireball 
#
# Allowed values: any item id or item name (default is red_rose)
# 
WandItem: red_rose

#
# CoolDownInterval: length of time, in seconds, between fireballs
#
# Allowed values: any number 0 or larger (default is 1)
# 
CoolDownInterval: 1

#
# RequireCommandToggle: toggle that determines if a command is required to enable fireballs
#
# Allowed values : Yes (player must use the /flowerpower command to enable/disable fireballs)
#                  No  (fireballs are always enabled when left clicking with the wand item)
# 
RequireCommandToggle: Yes

#
# TakeItemFromPlayer: toggle that determines if the wand item should be taken from the player
#                     when a fireball is thrown
#
# Allowed values : Yes (item is taken from player [only one if the player holds a stack])
#                  No  (no item is taken from player)
# 
TakeItemFromPlayer: No

#
# FireballYieldMultiplier: allows adjustment of the fireball explosion yield. A value of 1.0
#                          is equal to a standard ghast fireball. A value of 0.5 makes the
#                          fireballs half as powerful, and a value of 2.0 makes them twice
#                          as powerful. Be careful with very large values, you might crash
#                          your server
#
# Allowed values : Any number greater than zero
# 
FireballYieldMultiplier: 1.0

#
# ShowErrorsInClient: toggle that determines if permissions or other error messages
#                     are displayed client-side
#
# Allowed values : Yes (shows errors to players)
#                  No  (errors only show up in server console)
# 
ShowErrorsInClient: Yes
