name: FlowerPower
main: redsgreens.FlowerPower.FlowerPower
version: 0.2
website: http://forums.bukkit.org/threads/22375/
commands:
  flowerpower:
    description: 'Toggles throwing fireballs on or off' 
    usage: '/flowerpower (Enables or disables fireballs)'
